### ISSUE TITLE
Re:When chat app live (its not issue)

### ISSUE THREAD

**Issue by coolsharad** [Mahmoud-Italy/real-time-Private-Chat-using-Socket.io-Nodejs-mySql#2]
Hi Mahmoud
 
   It really script  and really easy to use, its working perfectly on my local system , but once i have transfer the site on main domain which have https on , i m facing issue which says  :ERR_CONNECTION_REFUSED , is we need to use server ip with port or i need to use domain name with port , http://127.0.0.1:port/ is this correct or i need to change some thing on it.
 thanks for your help in advance

**Comment by Mahmoud-Italy** [comment]
Hi Collshared,

Yeah, you have to include HTTPS configuration in yours code since you using HTTPS domains


so instead of doing this:

var express = require("express");
var app = express();
var server = require("http").createServer(app);
var io = require("socket.io")(server);


do this:

const express = require('express');
const app = express();
const fs = require('fs');
const options = {
   // you have to create key.pem, cert.pem files and include SSL certificate in thoses files you can find it in your server SSL status
    key: fs.readFileSync('your_path_to_key.pem'), 
    cert: fs.readFileSync('your_path_to_cert.pem') 
};
const server = require('https').createServer(options, app);
const io = require("socket.io")(server);

**Comment by coolsharad** [comment]
Hi 
  Thanks for reply , do i need to used .htacess file on Apache to get things are working perfectly
